[versions]

core = "1.19.0"
appcompat = "1.7.1"
material = "1.14.0"
fragment = "1.8.9"
coroutines = "1.11.0"
lifecycle = "2.11.0"
hilt = "2.60.1"
navigation = "2.9.8"
progressbar-circular = "3.1.0"
konfetti = "2.0.5"
timber = "5.0.1"
gravity-core = "1.0.46"

android = "9.2.1"
ksp = "2.3.9"

sdk-min = "26"
sdk-compile = "37"
sdk-target = "37"

[libraries]

core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
progressbar-circular = { group = "com.mikhaellopez", name = "circularprogressbar", version.ref = "progressbar-circular" }
konfetti = { group = "nl.dionsegijn", name = "konfetti-xml", version.ref = "konfetti" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
gravity-core = { group = "com.github.raheemadamboev", name = "core-sdk-android", version.ref = "gravity-core" }

[plugins]

android = { id = "com.android.application", version.ref = "android" }
library = { id = "com.android.library", version.ref = "android" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }